### ISSUE TITLE
results

### ISSUE THREAD

**Issue by InesArous** [liu-zichen/TEMP#1]
Hello,
Thanks a lot for sharing your source code.

By running your implementation as it is, I get the following numbers:
(0.11764705882352941, 0.19922585890322098, 0.5267232767232763)
If I understood correctly, these results should correspond to Table 2 science column.
However, the numbers are quite different.
Is there any special configuration to be able to reproduce the same numbers as in the paper?

Thanks!

**Comment by liu-zichen** [comment]
It may be caused by the loss not converging which is a common problem for margin loss. Retrying with another random seed when you found it doesn’t converge in the first few batches can solve the problem.

**Comment by InesArous** [comment]
Thank you for your prompt response.
I tried with six different seeds (0,1,2,3,17,48). I got similar results, and the model does not seem to converge.
The results are similar to the Bert+MLP performance reported in the paper.
Maybe the configuration is set for the baseline (Bert+MLP) and not Temp?
If so, can you please indicate how to configure the  TEMP method?
Thanks!

**Comment by liu-zichen** [comment]
The configuration is for the TEMP method.
There was something wrong with the seed configuration. I updated the seed config and the checking for "not converge".
Sorry for my mistake.
Please try with the new code.

**Comment by InesArous** [comment]
Great, now I get numbers closer to the ones reported in the paper 
(0.47058823529411764, 0.5993993352863486, 0.8359872153989797)
 thank you!
